import { createApp } from "@deroll/app";
import { encodeFunctionData, getAddress, hexToString } from "viem";
import contractAbi from "./abi.json";
var contract_address=""
const app=createApp({
  url:process.env.ROLLUP_HTTP_SERVER_URL || "http://127.0.0.1:5004",
});

app.addAdvanceHandler(async({payload})=>{
  const payloadString=hexToString(payload)
  console.log("payload",payload);
  const jsonPayload=JSON.parse(payloadString)
  if (jsonPayload.method==="set_address"){
     contract_address=getAddress(jsonPayload.address)
    console.log("Address is now set", contract_address)
  }else if(jsonPayload.method==="generate_number"){
    const cartesiGeneratedNumber=jsonPayload.number*2
    console.log("Number generated by cartesi backend is:",cartesiGeneratedNumber)

    // voucher!!
    const callData=encodeFunctionData({
      abi:contractAbi,
      functionNamee:"store",
      args:[cartesiGeneratedNumber]
    })
    // generate voucher
    app.createVoucher({destination:contract_address,payload:callData})
  }
  return "accept"
})

app.start().catch((e)=>{
  console.error(e);
  process.exit(1);
});